/**
 * Virtual Sim — Lore / Intro sentences (single source of truth)
 * Used by: game.html (cinematic crawl), index.html (Codex), quests, achievements
 */

const INTRO_LORE = [
  'HOPE IS SOMETHING WE CAN ALWAYS AFFORD',
  'LIFE IS SOMETHING MORE GREATER THAN YOU THINK',
  'YOU JUST GOTTA KNOW HOW TO LIVE IT',
  'THE LAND STRETCHES BEYOND WHAT ANY EYE CAN HOLD',
  'IN THE VASTNESS WE LEARN HOW SMALL WE ARE',
  'THE SKY HAS NO MERCY FOR THOSE WHO LOOK UP AND WEEP',
  'EVERY ROAD LEADS THROUGH THE SEVERE AND THE BEAUTIFUL',
  'SOME PLACES TAKE MORE THAN THEY GIVE',
  'YOU WILL WALK FOR MILES AND STILL BE NOWHERE',
  'THE EARTH REMEMBERS EVERY FOOTSTEP AND EVERY FALL',
  'IN THE WILD THERE IS NO PROMISE OF TOMORROW',
  'WE CAME TO THIS LAND BECAUSE WE HAD NOWHERE ELSE',
  'THE STARS DO NOT COMFORT THEY ONLY WATCH',
  'TO SURVIVE HERE IS TO ACCEPT THAT YOU ARE ALONE',
  'THE WIND CARRIES THE NAMES OF THOSE WHO DID NOT MAKE IT',
  'THIS WORLD WAS NOT BUILT FOR KINDNESS',
  'WE BUILD TOWERS IN THE HOPE THAT SOMEONE WILL SEE THEM',
  'THE NIGHT LASTS LONGER THAN THE DAY IN THESE PARTS',
  'MANY HAVE CROSSED THIS LAND AND FEW HAVE RETURNED',
  'THE GROUND HOLDS BONES THAT NO ONE COMES TO CLAIM',
  'YOU LEARN TO CARRY YOUR GRIEF LIKE A WEAPON',
  'THERE IS NO MAP FOR THE PLACES INSIDE YOU THAT BREAK',
  'THE VAST LAND FORGIVES NOTHING AND FORGETS NO ONE',
  'WE LIVE BECAUSE THE ALTERNATIVE IS TO STOP',
  'EVERY DAWN HERE FEELS LIKE A REPRIEVE NOT A GIFT',
  'THE SEVERE BEAUTY OF THIS PLACE WILL OUTLAST US ALL',
  'SOME DAYS THE ONLY THING YOU CAN DO IS WALK',
  'THE SKY AND THE EARTH MEET IN A LINE THAT NEVER ENDS',
  'WE CAME FROM SOMEWHERE ELSE AND WE WILL LEAVE AS STRANGERS',
  'THE LAND DOES NOT CARE IF YOU ARE READY',
  'HOPE IS THE THING YOU CLUTCH WHEN THE LIGHT GOES OUT',
  'TO LOVE THIS PLACE IS TO LOVE WHAT IT TAKES FROM YOU',
  'THE DISTANCE BETWEEN TWO POINTS IS ALWAYS FURTHER THAN IT LOOKS',
  'WE BUILD FIRES TO REMIND OURSELVES THAT WE ARE STILL ALIVE',
  'THE VAST OPEN LAND HAS NO DOORS AND NO EXIT',
  'EVERY SEASON HERE LEAVES ITS MARK ON YOUR FACE',
  'THE STARS ARE COLD WITNESSES TO EVERYTHING WE LOSE',
  'THIS WORLD IS SEVERE SO THAT ONLY THE STUBBORN REMAIN',
  'YOU LEARN THAT SOLITUDE IS NOT THE SAME AS PEACE',
  'THE LAND GIVES BACK NOTHING YOU DO NOT FIGHT FOR',
  'WE MARCH BECAUSE STANDING STILL IS A KIND OF DEATH',
  'THE SKY HAS SEEN TOO MUCH TO OFFER COMFORT',
  'IN THE VAST AND SEVERE WE FIND OUT WHO WE REALLY ARE',
  'EVERY FOOTPRINT IN THE DUST IS A PRAYER FOR SOMETHING MORE',
  'THE NIGHT HERE HAS NO BOTTOM AND NO EDGE',
  'WE CARRY THE WEIGHT OF PLACES WE CAN NEVER RETURN TO',
  'THE LAND REMEMBERS EVERY WAR EVERY FALL EVERY SILENCE',
  'TO LIVE HERE IS TO ACCEPT THAT BEAUTY AND LOSS ARE THE SAME',
  'THE VAST SEVERE LAND DOES NOT PROMISE YOU A HOME',
  'BUT WE GO ON BECAUSE GOING ON IS THE ONLY THING LEFT TO DO'
];

if (typeof window !== 'undefined') {
  window.INTRO_LORE = INTRO_LORE;
}
